# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: to_do_app_db
    image: postgres:9.6.21-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
